Create PT2ASS7***11.12.23.17:41
o integrate the two programs, you can simply copy the code from the second program into the first program, after the main function. This will make the caesarEncode() and caesarDecode() functions available to the processFile() function.

Here is the integrated program:

C++
#include <iostream>
#include <fstream>

using namespace std;

// Declare the caesarEncode() and caesarDecode() functions.
string caesarEncode(string line, int key);
string caesarDecode(string line, int key);

void processFile(string inputFilename, string outputFilename, int key, string encodeDecode);

int main() {
  // Welcome the user.
  cout << "Welcome to the encoding and decoding program!" << endl;

  // Ask the user if they would like to encode or decode a message.
  string encodeDecode;
  cout << "Would you like to encode or decode a message? (e/d): ";
  cin >> encodeDecode;

  // Ask the user for the input filename.
  string inputFilename;
  cout << "Enter the input filename: ";
  cin >> inputFilename;

  // Ask the user for the output filename.
  string outputFilename;
  cout << "Enter the output filename: ";
  cin >> outputFilename;

  // Ask the user for an integer key value.
  int key;
  cout << "Enter an integer key value: ";
  cin >> key;

  // Call the processFile function.
  processFile(inputFilename, outputFilename, key, encodeDecode);

  return 0;
}

void processFile(string inputFilename, string outputFilename, int key, string encodeDecode) {
  // Create an ifstream named inFile connecting your program to inputFileName.
  ifstream inFile(inputFilename);

  // Check that inFile opened correctly. If not, exit the program.
  if (!inFile.is_open()) {
    cout << "Error opening input file: " << inputFilename << endl;
    exit(1);
  }

  // Create an ofstream named outFile connecting your program to outputFileName.
  ofstream outFile(outputFilename);

  // Check that outFile opened correctly. If not, exit the program.
  if (!outFile.is_open()) {
    cout << "Error opening output file: " << outputFilename << endl;
    exit(1);
  }

  // Read the input file line by line.
  string line;
  while (getline(inFile, line)) {
    // Encode or decode the line.
    string encodedOrDecodedLine;
    if (encodeDecode == "e") {
      encodedOrDecodedLine = caesarEncode(line, key);
    } else if (encodeDecode == "d") {
      encodedOrDecodedLine = caesarDecode(line, key);
    } else {
      cout << "Invalid encode/decode parameter: " << encodeDecode << endl;
      exit(1);
    }

    // Write the encoded or decoded line to the output file.
    outFile << encodedOrDecodedLine << endl;
  }

  // When file operations are complete, close all ifstream and ofstream connections.
  inFile.close();
  outFile.close();
}

// Implement the caesarEncode() and caesarDecode() functions here.
Use code with caution. Learn more
You can now compile and run the integrated program. It should be able to encode and decode files without any errors.

profile picture
CONSIDER THIS ERROR ....error: undefined symbol: _Z12caesarDecodeNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi (referenced by top-level compiled C/C++ code)
warning: Link with `-sLLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: __Z12caesarDecodeNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _Z12caesarEncodeNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi (referenced by top-level compiled C/C++ code)
warning: __Z12caesarEncodeNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEi may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
AND CORRECT PROGRAM...#include <iostream>
#include <fstream>

using namespace std;

// Declare the caesarEncode() and caesarDecode() functions.
string caesarEncode(string line, int key);
string caesarDecode(string line, int key);

void processFile(string inputFilename, string outputFilename, int key, string encodeDecode);

int main() {
 // Welcome the user.
 cout << "Welcome to the encoding and decoding program!" << endl;

 // Ask the user if they would like to encode or decode a message.
 string encodeDecode;
 cout << "Would you like to encode or decode a message? (e/d): ";
 cin >> encodeDecode;

 // Ask the user for the input filename.
 string inputFilename;
 cout << "Enter the input filename: ";
 cin >> inputFilename;

 // Ask the user for the output filename.
 string outputFilename;
 cout << "Enter the output filename: ";
 cin >> outputFilename;

 // Ask the user for an integer key value.
 int key;
 cout << "Enter an integer key value: ";
 cin >> key;

 // Call the processFile function.
 processFile(inputFilename, outputFilename, key, encodeDecode);

 return 0;
}

void processFile(string inputFilename, string outputFilename, int key, string encodeDecode) {
 // Create an ifstream named inFile connecting your program to inputFileName.
 ifstream inFile(inputFilename);

 // Check that inFile opened correctly. If not, exit the program.
 if (!inFile.is_open()) {
  cout << "Error opening input file: " << inputFilename << endl;
  exit(1);
 }

 // Create an ofstream named outFile connecting your program to outputFileName.
 ofstream outFile(outputFilename);

 // Check that outFile opened correctly. If not, exit the program.
 if (!outFile.is_open()) {
  cout << "Error opening output file: " << outputFilename << endl;
  exit(1);
 }

 // Read the input file line by line.
 string line;
 while (getline(inFile, line)) {
  // Encode or decode the line.
  string encodedOrDecodedLine;
  if (encodeDecode == "e") {
   encodedOrDecodedLine = caesarEncode(line, key);
  } else if (encodeDecode == "d") {
   encodedOrDecodedLine = caesarDecode(line, key);
  } else {
   cout << "Invalid encode/decode parameter: " << encodeDecode << endl;
   exit(1);
  }

  // Write the encoded or decoded line to the output file.
  outFile << encodedOrDecodedLine << endl;
 }

 // When file operations are complete, close all ifstream and ofstream connections.
 inFile.close();
 outFile.close();
}

// Implement the caesarEncode() and caesarDecode() functions here....ACCORDINGLY
View other drafts




















The error message indicates that the linker cannot find the definitions for the caesarEncode() and caesarDecode() functions. This can happen if the functions are not defined in the same source file as the main function, or if they are not exported from the library or object file where they are defined.

To fix the error, you need to make sure that the caesarEncode() and caesarDecode() functions are defined and exported before the linker tries to link them. You can do this by:

Defining the functions in the same source file as the main function.
Exporting the functions from the library or object file where they are defined.
Here is an example of how to export the functions:

C++
// Define the caesarEncode() and caesarDecode() functions.

extern "C" {
  string caesarEncode(string line, int key);
  string caesarDecode(string line, int key);
}
Use code with caution. Learn more
The extern "C" keyword tells the compiler to export the functions with C-style linkage, which is required by the linker.

Once you have exported the functions, you can compile and link your program without any errors.

Corrected program:

C++
#include <iostream>
#include <fstream>

using namespace std;

// Declare the caesarEncode() and caesarDecode() functions.
extern "C" {
  string caesarEncode(string line, int key);
  string caesarDecode(string line, int key);
}

void processFile(string inputFilename, string outputFilename, int key, string encodeDecode);

int main() {
  // Welcome the user.
  cout << "Welcome to the encoding and decoding program!" << endl;

  // Ask the user if they would like to encode or decode a message.
  string encodeDecode;
  cout << "Would you like to encode or decode a message? (e/d): ";
  cin >> encodeDecode;

  // Ask the user for the input filename.
  string inputFilename;
  cout << "Enter the input filename: ";
  cin >> inputFilename;

  // Ask the user for the output filename.
  string outputFilename;
  cout << "Enter the output filename: ";
  cin >> outputFilename;

  // Ask the user for an integer key value.
  int key;
  cout << "Enter an integer key value: ";
  cin >> key;

  // Call the processFile function.
  processFile(inputFilename, outputFilename, key, encodeDecode);

  return 0;
}

void processFile(string inputFilename, string outputFilename, int key, string encodeDecode) {
  // Create an ifstream named inFile connecting your program to inputFileName.
  ifstream inFile(inputFilename);

  // Check that inFile opened correctly. If not, exit the program.
  if (!inFile.is_open()) {
    cout << "Error opening input file: " << inputFilename << endl;
    exit(1);
  }

  // Create an ofstream named outFile connecting your program to outputFileName.
  ofstream outFile(outputFilename);

  // Check that outFile opened correctly. If not, exit the program.
  if (!outFile.is_open()) {
    cout << "Error opening output file: " << outputFilename << endl;
    exit(1);
  }

  // Read the input file line by line.
  string line;
  while (getline(inFile, line)) {
    // Encode or decode the line.
    string encodedOrDecodedLine;
    if (encodeDecode == "e") {
      encodedOrDecodedLine = caesarEncode(line, key);
    } else if (encodeDecode == "d") {
      encodedOrDecodedLine = caesarDecode(line, key);
    } else {
      cout << "Invalid encode/decode parameter: " << encodeDecode << endl;
      exit(1);
    }

    // Write the encoded or decoded line to the output file.
    outFile << encodedOrDecodedLine << endl;
  }

  // When file operations are complete, close all ifstream and ofstream connections.
  inFile.close();
  outFile.close();